config/routes.rb
Art::Application.routes.draw do
  resources :orders

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :posts

  resources :artworks

  resources :artists

  resources :users
  
  resources :sessions
  
  
  
	match '/signin'   => "sessions#new"
	match '/signout'  => "sessions#destroy"
	
	match '/about' => "pages#about"
	 match '/search' => 'artists#search'

  
   
   root :to => 'pages#home'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :artworks 
	validates :name, presence: true
	validates :dob, presence: true
	
	 def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['title LIKE  ?', search_condition])
end
	
	def username
	username = self.name + " " + self.email
	end
	
	def age
	age = ((Date.current - self.dob)/365).to_i
	end
	
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
  before_filter :authorise, :only => [:new, :edit, :delete]
  
  def index
    @artists = Artist.paginate(:page => params[:page], :per_page => 2)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end
  
  def search
    @artists = Artist.paginate(:page => params[:page], :per_page => 2).search params[:q]
	
	unless @artists.empty?
		render 'index'
	else
		flash[:notice] = 'No artists match that search, Please try again'
		render 'index'
    end
		flash[:notice] = null
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>
	  
      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.select :name,["Beuwick","Picasso","Van Gogh","other"] %>
  </div>
  
   <div class="field">
    <%= f.label :dob %><br />
    <%= f.text_field :dob, :id => :datepicker %>
  </div>
  
 
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/_search.html.erb
<%= form_tag("/search", :method => "get") do %>
   <%= label_tag(:q, "Search for:") %>
   <%= text_field_tag(:q, params[:q], :id => 'q_field') %>
   <%= submit_tag("Search") %>
<% end %> 

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<%= will_paginate @artists %>

<table>
  <tr>
    <th>Name</th>
    <th>Dob</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
  
  <div id="search">
	  <%= render :partial => 'artists/search' %>
 </div>

<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.name %></td>
    <td><%= artist.dob %></td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>

<p>
  <b>Dob:</b>
  <%= @artist.dob %>
</p>

<b>age:</b>
  <%= @artist.age %>
</p>
<p>

	#<b>artworks for this artist: </b> <br \>
	#<% @artist.artworks.each do |m| %>
	#<%= m.title %>
	#<br \>
	#<% end %>
	
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>
<p id="notice"><%= notice %></p>

<p>

	