config/routes.rb
Art::Application.routes.draw do
  resources :orders

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :posts

  resources :artworks

  resources :artists

  resources :users
  
  resources :sessions
  
  
  
	match '/signin'   => "sessions#new"
	match '/signout'  => "sessions#destroy"
	
	match '/about' => "pages#about"
	 match '/search' => 'artists#search'

  
   
   root :to => 'pages#home'

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
	belongs_to :artist
	validates :title, presence: true
	validates :age, presence: true	
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  # GET /artworks
  # GET /artworks.json
  before_filter :authorise, :only => [:new, :edit, :delete]
  def index
    @artworks = Artwork.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artworks }
    end
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
    @artwork = Artwork.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artwork }
    end
  end

  # GET /artworks/new
  # GET /artworks/new.json
  def new
    @artwork = Artwork.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artwork }
    end
  end

  # GET /artworks/1/edit
  def edit
    @artwork = Artwork.find(params[:id])
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(params[:artwork])

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render json: @artwork, status: :created, location: @artwork }
      else
        format.html { render action: "new" }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artworks/1
  # PUT /artworks/1.json
  def update
    @artwork = Artwork.find(params[:id])

    respond_to do |format|
      if @artwork.update_attributes(params[:artwork])
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy

    respond_to do |format|
      format.html { redirect_to artworks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/_form.html.erb
<%= form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artworkimage %><br />
    <%= f.text_field :artworkimage %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.date_select :age %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.number_field :artist_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.select :type,["50-100","100-200","200-300","300+"]%>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :type,["sculpture","painting","watercolour","pottery"]%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<h1>Listing artworks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Artworkimage</th>
    <th>Age</th>
    <th>Artist</th>
    <th>Price</th>
    <th>Type1</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artworks.each do |artwork| %>
  <tr>
    <td><%= artwork.title %></td>
    <td><%= artwork.artworkimage %></td>
    <td><%= artwork.age %></td>
    <td><%= artwork.artist_id %></td>
    <td><%= artwork.price %></td>
    <td><%= artwork.type1 %></td>
    <td><%= link_to 'Show', artwork %></td>
    <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
    <td><%= link_to 'Destroy', artwork, confirm: 'Are you sure?', method: :delete %></td>
	<td><%= button_to 'Buy This Artwork', new_order_path(oid: artwork) %></td>
	
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artwork', new_artwork_path %>

app/views/artworks/new.html.erb
<h1>New artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @artwork.title %>
</p>

<p>
  <b>Artworkimage:</b>
 <%= image_tag(@movie.poster, :size => "30x30") %>
</p>

<p>
  <b>Age:</b>
  <%= @artwork.age %>
</p>

<p>
  <b>Artist:</b>
  <%= @artwork.artist.number %>
</p>

<p>
  <b>Price:</b>
  <%= @artwork.price %>
</p>

<p>
  <b>Type1:</b>
  <%= @artwork.name %>
</p>


<%= link_to 'Edit', edit_artwork_path(@artwork) %> |
<%= link_to 'Back', artworks_path %>